=== apple/ccs-caldavtester/trunk/scripts/tests-pod/CalDAV/caldavtest.dtd
<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<!ELEMENT caldavtest (description?, require-feature?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT require-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>
	<!ELEMENT exclude-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT pause EMPTY>

	<!ELEMENT request (require-feature?, exclude-feature?, method, ruri*, header*, data?, verify*,
						graburi?, grabcount?, grabheader*, grabproperty*, grabelement*, grabcalproperty*, grabcalparameter*)>
		<!ATTLIST request host2 (yes|no) "no"
						 auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no"
						 iterate-data (yes|no) "no"
						 wait-for-success (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT data (content-type, filepath)>
			<!ATTLIST data substitutions (yes|no) "yes"
			               generate      (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>

		<!ELEMENT verify (require-feature?, exclude-feature?, callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value*)>
		
		<!ELEMENT graburi (#PCDATA)>

		<!ELEMENT grabcount (#PCDATA)>

		<!ELEMENT grabheader (name, variable)>
	
		<!ELEMENT grabproperty (property, variable)>
			<!ELEMENT property (#PCDATA)>
			<!ELEMENT variable (#PCDATA)>

		<!ELEMENT grabelement (name, parent*, variable+)>

		<!ELEMENT grabcalproperty (name, variable)>
		<!ELEMENT grabcalparameter (name, variable)>

	<!ELEMENT test-suite (require-feature?, exclude-feature?, test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no"
							only (yes|no) "no">
	
		<!ELEMENT test (require-feature?, exclude-feature?, description?, (request|pause)+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no"
						  only (yes|no) "no">

=== apple/ccs-caldavtester/trunk/scripts/tests/CalDAV/conditional.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test ACLs on the server</description>

	<require-feature>
		<feature>caldav</feature>
	</require-feature>

	<start/>
	
	<test-suite name='Last_modified handling' ignore='no'>

		<test name='1' ignore='no'>
			<description>Regular PROPFIND</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$calendarpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/displayname.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>207</value>
					</arg>
				</verify>
				<grabheader>
					<name>Last-Modified</name>
					<variable>$last-modified:</variable>
				</grabheader>
			</request>
		</test>

		<test name='2' ignore='no'>
			<description>Regular PROPFIND</description>
			<request print-response='no'>
				<method>DELAY</method>
				<ruri>2</ruri>
			</request>
		</test>

		<test name='3' ignore='no'>
			<description>Conditional PROPFIND</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$calendarpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<header>
					<name>If-Modified-Since</name>
					<value>$last-modified:</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/displayname.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>304</value>
					</arg>
				</verify>
			</request>
		</test>

	</test-suite>
	
	<end/>
	
</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CardDAV/sharing-replies.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test addressbook sharing replies</description>

	<require-feature>
		<feature>carddav</feature>
		<feature>shared-addressbooks</feature>
	</require-feature>

	<start>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$addressbookhome1:/</ruri>
			<ruri>$addressbookhome2:/</ruri>
			<ruri>$notificationpath1:/</ruri>
			<ruri>$notificationpath2:/</ruri>
		</request>
	</start>
	
	<test-suite name='Send first reply' ignore='no'>
		<test name='1' ignore='no'>
			<description>POST invitation</description>
			<request print-response='no'>
				<method>POST</method>
				<ruri>$addressbookpath1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/sharing/replies/accept/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Check Sharee notification collection</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>WAITCOUNT 1</method>
				<ruri>$notificationpath2:/</ruri>
			</request>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$notificationpath2:/</ruri>
				<verify>
					<callback>xmlDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CardDAV/sharing/replies/accept/2.xml</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>{http://calendarserver.org/ns/}dtstamp</value>
						<value>{http://calendarserver.org/ns/}uid</value>
					</arg>
				</verify>
				<grabelement>
					<name>{http://calendarserver.org/ns/}invite-notification/{http://calendarserver.org/ns/}uid</name>
					<variable>$inviteuid:</variable>
				</grabelement>
			</request>
		</test>
		<test name='3'>
			<description>Sharee replies ACCEPTED</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>POST</method>
				<ruri>$addressbookhome2:/</ruri>
				<data substitutions='yes'>
					<content-type>application/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/sharing/replies/accept/3.xml</filepath>
				</data>
				<verify>
					<callback>xmlDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CardDAV/sharing/replies/accept/7.xml</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>{DAV:}href</value>
					</arg>
				</verify>
				<grabelement>
					<name>{DAV:}href</name>
					<variable>$shareeaddressbook:</variable>
				</grabelement>
			</request>
		</test>
		<test name='4' ignore='no'>
			<description>Check accept status</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/sharing/replies/accept/4.xml</filepath>
				</data>
				<verify>
					<callback>xmlDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CardDAV/sharing/replies/accept/5.xml</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>{http://calendarserver.org/ns/}uid</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>Check Sharer notification collection</description>
			<request>
				<method>WAITCOUNT 1</method>
				<ruri>$notificationpath1:/</ruri>
			</request>
			<request print-response='no'>
				<method>GETNEW</method>
				<ruri>$notificationpath1:/</ruri>
				<verify>
					<callback>xmlDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CardDAV/sharing/replies/accept/6.xml</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>{http://calendarserver.org/ns/}dtstamp</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='6' ignore='no'>
			<description>Check sharee addressbook displayname/shared-url</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$shareeaddressbook:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/sharing/replies/accept/8.xml</filepath>
				</data>
				<verify>
					<callback>propfindValues</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}displayname$My Shared Address Book</value>
						<value>{http://calendarserver.org/ns/}sharedurl$$calendarhome1:/shared</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='7' ignore='no'>
			<description>Check sharer addressbook displyname</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/displayname.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>badprops</name>
						<value>{DAV:}displayname</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Update reply' ignore='no'>
		<test name='1'>
			<description>Sharee replies DECLINED</description>
			<request user="$userid2:" pswd="$pswd2:" print-response='no'>
				<method>POST</method>
				<ruri>$addressbookhome2:/</ruri>
				<data substitutions='yes'>
					<content-type>application/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/sharing/replies/decline/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>Check declined status</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/sharing/replies/decline/2.xml</filepath>
				</data>
				<verify>
					<callback>xmlDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CardDAV/sharing/replies/decline/3.xml</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>{http://calendarserver.org/ns/}uid</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Check Sharer notification collection</description>
			<request>
				<method>WAITCOUNT 1</method>
				<ruri>$notificationpath1:/</ruri>
			</request>
			<request print-response='no'>
				<method>GETNEW</method>
				<ruri>$notificationpath1:/</ruri>
				<verify>
					<callback>xmlDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CardDAV/sharing/replies/decline/4.xml</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>{http://calendarserver.org/ns/}dtstamp</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$addressbookhome1:/</ruri>
			<ruri>$addressbookhome2:/</ruri>
			<ruri>$notificationpath1:/</ruri>
			<ruri>$notificationpath2:/</ruri>
		</request>
	</end>

</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CardDAV/directory-gateway.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test GET on collections to ensure proper directory listing</description>
	
	<require-feature>
		<feature>carddav</feature>
		<feature>directory-gateway</feature>
	</require-feature>

	<start/>

	<test-suite name='Find the gateway'>
		<test name='1'>
			<description>PROPFIND of principal for gateway</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$principal1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/directory-gateway/1.xml</filepath>
				</data>
				<verify>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>exists</name>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:carddav}directory-gateway</value>
					</arg>
				</verify>
				<grabelement>
					<name>/{DAV:}multistatus/{DAV:}response/{DAV:}propstat/{DAV:}prop/{urn:ietf:params:xml:ns:carddav}directory-gateway/{DAV:}href</name>
					<variable>$gateway1:</variable>
				</grabelement>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of gateway</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$gateway1:</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/resourcetype.xml</filepath>
				</data>
				<verify>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>exists</name>
						<value>$verify-property-prefix:/{DAV:}resourcetype/{DAV:}collection</value>
						<value>$verify-property-prefix:/{DAV:}resourcetype/{urn:ietf:params:xml:ns:carddav}addressbook</value>
						<value>$verify-property-prefix:/{DAV:}resourcetype/{urn:ietf:params:xml:ns:carddav}directory</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of gateway: DAV:resource-id</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$gateway1:</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/resourceid.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}resource-id</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>PROPFIND of gateway: no sync report</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$gateway1:</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/supported-report-set.xml</filepath>
				</data>
				<verify>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>notexists</name>
						<value>$verify-property-prefix:/{DAV:}supported-report-set/{DAV:}supported-report/{DAV:}report/{DAV:}sync-collection</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>GET of gateway</description>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$directory:</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>
	
</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CalDAV/proxyauthz.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test proxy authorization on the server</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>proxy-authz</feature>
	</require-feature>

	<start>
		<request end-delete="yes">
			<method>PUT</method>
			<ruri>$calendarpath1:/1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/CalDAV/delete/1.txt</filepath>
			</data>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>MKCALENDAR</method>
			<ruri>$calendarhome2:/visibletouser01/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>ACL</method>
			<ruri>$calendarhome2:/visibletouser01/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/CalDAV/acls/3.xml</filepath>
			</data>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>PUT</method>
			<ruri>$calendarhome2:/visibletouser01/hidden1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/CalDAV/acls/16.ics</filepath>
			</data>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>PUT</method>
			<ruri>$calendarhome2:/visibletouser01/visible2.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/CalDAV/acls/17.ics</filepath>
			</data>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>MKCALENDAR</method>
			<ruri>$calendarhome2:/notvisibletouser01/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>ACL</method>
			<ruri>$calendarhome2:/notvisibletouser01/</ruri>
			<data>
				<content-type>text/xml; charset=utf-8</content-type>
				<filepath>Resource/CalDAV/acls/21.xml</filepath>
			</data>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>PUT</method>
			<ruri>$calendarhome2:/notvisibletouser01/hidden1.ics</ruri>
			<data>
				<content-type>text/calendar; charset=utf-8</content-type>
				<filepath>Resource/CalDAV/acls/16.ics</filepath>
			</data>
		</request>
	</start>
	
	<test-suite name='Valid Proxy User' ignore='no'>
		<test name='1' ignore='no'>
			<description>GET user01 resource</description>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>$userid1:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>GET user02 resource</description>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarhome2:/visibletouser01/visible2.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>$userid1:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3' ignore='no'>
			<require-feature>
				<feature>per-object-ACLs</feature>
			</require-feature>
			<description>GET user02 resource</description>
			<request user="$userid2:" pswd="$pswd2:">
				<method>ACL</method>
				<ruri>$calendarhome2:/visibletouser01/hidden1.ics</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/acls/20.xml</filepath>
				</data>
			</request>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarhome2:/visibletouser01/hidden1.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>$userid1:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4' ignore='no'>
			<description>GET user02 resource</description>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarhome2:/notvisibletouser01/hidden1.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>$userid1:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='Wrong Proxy User' ignore='no'>
		<test name='1' ignore='no'>
			<description>GET user01 resource</description>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>$userid3:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<require-feature>
				<feature>per-object-ACLs</feature>
			</require-feature>
			<description>GET user02 resource</description>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarhome2:/visibletouser01/visible2.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>$userid3:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3' ignore='no'>
			<require-feature>
				<feature>per-object-ACLs</feature>
			</require-feature>
			<description>GET user02 resource</description>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarhome2:/visibletouser01/hidden1.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>$userid3:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4' ignore='no'>
			<require-feature>
				<feature>per-object-ACLs</feature>
			</require-feature>
			<description>GET user02 resource</description>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarhome2:/notvisibletouser01/hidden1.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>$userid3:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='Invalid Proxy User' ignore='no'>
		<test name='1' ignore='no'>
			<description>Valid proxy without header</description>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>400</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>Valid proxy proxying as another proxy</description>
			<request user="$userproxy:" pswd="$pswdproxy:" print-response='no'>
				<method>GET</method>
				<ruri>$calendarhome2:/visibletouser01/visible2.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>proxy2</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3' ignore='no'>
			<description>Regular user trying to proxy</description>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$calendarhome2:/visibletouser01/visible2.ics</ruri>
				<header>
					<name>X-Authorize-As</name>
					<value>$userid2:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end>
		<request user="$userid2:" pswd="$pswd2:">
			<method>DELETE</method>
			<ruri>$calendarhome2:/visibletouser01/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>DELETE</method>
			<ruri>$calendarhome2:/notvisibletouser01/</ruri>
		</request>
	</end>
	
</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CalDAV/implicitoptions.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test implicit scheduling options in CalDAV</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>implicit-scheduling</feature>
	</require-feature>

	<start/>
	
	<test-suite name='OPTIONS header' ignore='no'>
		<test name='1'>
			<description>Look for options header tag on principal</description>
			<request print-response="no">
				<method>OPTIONS</method>
				<ruri>$principal1:</ruri>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>*DAV$.*calendar-access.*</value>
						<value>*DAV$.*calendar-schedule.*</value>
						<value>*DAV$.*calendar-auto-schedule.*</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Look for options header tag on calendar</description>
			<request print-response="no">
				<method>OPTIONS</method>
				<ruri>$calendarpath1:/</ruri>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>*DAV$.*calendar-access.*</value>
						<value>*DAV$.*calendar-schedule.*</value>
						<value>*DAV$.*calendar-auto-schedule.*</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>
