=== apple/ccs-caldavtester/trunk/scripts/tests-pod/CalDAV/caldavtest.dtd
<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<!ELEMENT caldavtest (description?, require-feature?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT require-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>
	<!ELEMENT exclude-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT pause EMPTY>

	<!ELEMENT request (require-feature?, exclude-feature?, method, ruri*, header*, data?, verify*,
						graburi?, grabcount?, grabheader*, grabproperty*, grabelement*, grabcalproperty*, grabcalparameter*)>
		<!ATTLIST request host2 (yes|no) "no"
						 auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no"
						 iterate-data (yes|no) "no"
						 wait-for-success (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT data (content-type, filepath)>
			<!ATTLIST data substitutions (yes|no) "yes"
			               generate      (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>

		<!ELEMENT verify (require-feature?, exclude-feature?, callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value*)>
		
		<!ELEMENT graburi (#PCDATA)>

		<!ELEMENT grabcount (#PCDATA)>

		<!ELEMENT grabheader (name, variable)>
	
		<!ELEMENT grabproperty (property, variable)>
			<!ELEMENT property (#PCDATA)>
			<!ELEMENT variable (#PCDATA)>

		<!ELEMENT grabelement (name, parent*, variable+)>

		<!ELEMENT grabcalproperty (name, variable)>
		<!ELEMENT grabcalparameter (name, variable)>

	<!ELEMENT test-suite (require-feature?, exclude-feature?, test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no"
							only (yes|no) "no">
	
		<!ELEMENT test (require-feature?, exclude-feature?, description?, (request|pause)+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no"
						  only (yes|no) "no">

=== apple/ccs-caldavtester/trunk/scripts/tests/CalDAV/limits.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest ignore-all="no">
	<description>Test Quota support on the server</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>limits</feature>
	</require-feature>

	<start/>
	
	<test-suite name='Limits in properties' ignore='no'>
		<test name='1'>
			<description>max-collections property</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>application/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/max-collections.xml</filepath>
				</data>
				<verify>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>exists</name>
						<value>$verify-property-prefix:/{http://calendarserver.org/ns/}max-collections[=50]</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>max-resources property</description>
			<request print-response='no'>
				<method>PROPFIND</method>
				<ruri>$calendarpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>application/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/max-resources.xml</filepath>
				</data>
				<verify>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>exists</name>
						<value>$verify-property-prefix:/{http://calendarserver.org/ns/}max-resources[=10000]</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='Collection limit' ignore='no'>
		<test name='1a' count='48' ignore='no'>
			<exclude-feature>
				<feature>split-calendars</feature>
			</exclude-feature>
			<description>Create collections to one below the limit</description>
			<request end-delete='yes' print-response='no'>
				<method>MKCALENDAR</method>
				<ruri>$calendarhome1:/caltest-##/</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>201</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='1b' count='47' ignore='no'>
			<require-feature>
				<feature>split-calendars</feature>
			</require-feature>
			<description>Create collections to one below the limit</description>
			<request end-delete='yes' print-response='no'>
				<method>MKCALENDAR</method>
				<ruri>$calendarhome1:/caltest-##/</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>201</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>Create collections to the limit</description>
			<request print-response='no'>
				<method>MKCALENDAR</method>
				<ruri>$calendarhome1:/caltest-49/</ruri>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>{http://calendarserver.org/ns/}max-collections</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>
	
</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CalDAV/alarm-dismissal.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test alarm dismissal behavior</description>

	<require-feature>
		<feature>caldav</feature>
	</require-feature>

	<start/>
	
	<test-suite name='Simple dismissal'>
		<test name='1'>
			<description>PUT event with alarm</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/alarm-dismissal/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Verify data</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/alarm-dismissal/1.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PUT event with ack'd alarm</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/alarm-dismissal/2.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>Verify data</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/alarm-dismissal/2.ics</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='Recurring dismissal'>
		<test name='1'>
			<description>PUT event with alarm</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/2.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/alarm-dismissal/3.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Verify data</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/2.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/alarm-dismissal/3.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PUT event with ack'd alarm</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/2.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/alarm-dismissal/4.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>Verify data</description>
			<request>
				<method>GET</method>
				<ruri>$calendarpath1:/2.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/alarm-dismissal/4.ics</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='Bad property value'>
		<test name='1'>
			<description>PUT event with alarm</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/3.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/alarm-dismissal/5.ics</filepath>
				</data>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>{urn:ietf:params:xml:ns:caldav}valid-calendar-data</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end>
		<request>
			<method>DELETEALL</method>
			<ruri>$calendarpath1:/</ruri>
		</request>
	</end>
	
</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CardDAV/ab-client.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Emulate the common behaviors of the AB client</description>

	<require-feature>
		<feature>carddav</feature>
	</require-feature>

	<start/>
	
	<test-suite name='Account setup'>
		<test name='1'>
			<description>PROPFIND principal - no authentication</description>
			<request auth="no">
				<method>PROPFIND</method>
				<ruri>$principal1:</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vab-client/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>401</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND principal - with authentication</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$principal1:</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vab-client/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>207</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='Polling'>
		<test name='1'>
			<description>PROPFIND addressbook home</description>
			<request print-response="no">
				<method>PROPFIND</method>
				<ruri>$addressbookhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vab-client/2.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>207</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CalDAV/polls.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test PUT method in CalDAV</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>vpoll</feature>
	</require-feature>

	<start/>

	<test-suite name='supported-component-set'>
		<test name='1'>
			<require-feature>
				<feature>supported-component-sets</feature>
			</require-feature>
			<description>Check calendar home for property</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/polls/supported-component-set/1.xml</filepath>
				</data>
				<verify>
					<exclude-feature>
						<feature>supported-component-sets-one</feature>
					</exclude-feature>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{urn:ietf:params:xml:ns:caldav}supported-calendar-component-sets$</value>
					</arg>
				</verify>
				<verify>
					<require-feature>
						<feature>supported-component-sets-one</feature>
					</require-feature>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>exists</name>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-sets/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set/{urn:ietf:params:xml:ns:caldav}comp[@name="VEVENT"]</value>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-sets/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set/{urn:ietf:params:xml:ns:caldav}comp[@name="VTODO"]</value>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-sets/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set/{urn:ietf:params:xml:ns:caldav}comp[@name="VPOLL"]</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Check calendar for property</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$pollspath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/polls/supported-component-set/2.xml</filepath>
				</data>
				<verify>
					<require-feature>
						<feature>exclude-calendars</feature>
					</require-feature>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>exists</name>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set/{urn:ietf:params:xml:ns:caldav}comp[@name="VEVENT"]</value>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set/{urn:ietf:params:xml:ns:caldav}comp[@name="VTODO"]</value>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set/{urn:ietf:params:xml:ns:caldav}comp[@name="VPOLL"]</value>
					</arg>
				</verify>
				<verify>
					<require-feature>
						<feature>split-calendars</feature>
					</require-feature>
					<callback>xmlElementMatch</callback>
					<arg>
						<name>exists</name>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set/{urn:ietf:params:xml:ns:caldav}comp[@name="VPOLL"]</value>
					</arg>
					<arg>
						<name>notexists</name>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set/{urn:ietf:params:xml:ns:caldav}comp[@name="VEVENT"]</value>
						<value>$verify-property-prefix:/{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set/{urn:ietf:params:xml:ns:caldav}comp[@name="VTODO"]</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='PUT VPOLL' ignore='no'>
		<test name='1' ignore='no'>
			<description>PUT unscheduled empty poll</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>$pollspath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/polls/put/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request>
				<method>GET</method>
				<ruri>$pollspath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/polls/put/2.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>PUT unscheduled event poll</description>
			<request end-delete='yes'>
				<method>PUT</method>
				<ruri>$pollspath1:/2.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/polls/put/3.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request>
				<method>GET</method>
				<ruri>$pollspath1:/2.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/polls/put/4.ics</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests-pod/CalDAV/simple.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Simple podding test</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>podding</feature>
	</require-feature>

	<start/>
	
	<test-suite name='Access principals via podA'>
		<test name='1'>
			<description>PROPFIND of user on podA as user on podA</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$principal1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of user on podB as user on podA</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$pprincipal1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of user on podA as user on podB</description>
			<request user='$puserid1:' pswd='$ppswd1:'>
				<method>PROPFIND</method>
				<ruri>$principal1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>PROPFIND of user on podB as user on podB</description>
			<request user='$puserid1:' pswd='$ppswd1:'>
				<method>PROPFIND</method>
				<ruri>$pprincipal1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='Access principals via podB'>
		<test name='1'>
			<description>PROPFIND of user on podA as user on podA</description>
			<request host2='yes'>
				<method>PROPFIND</method>
				<ruri>$principal1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of user on podB as user on podA</description>
			<request host2='yes'>
				<method>PROPFIND</method>
				<ruri>$pprincipal1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of user on podA as user on podB</description>
			<request host2='yes' user='$puserid1:' pswd='$ppswd1:'>
				<method>PROPFIND</method>
				<ruri>$principal1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>PROPFIND of user on podB as user on podB</description>
			<request host2='yes' user='$puserid1:' pswd='$ppswd1:'>
				<method>PROPFIND</method>
				<ruri>$pprincipal1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='Access calendar homes via podA'>
		<test name='1'>
			<description>PROPFIND of user on podA as user on podA</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of user on podB as user on podA</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$pcalendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of user on podA as user on podB</description>
			<request user='$puserid1:' pswd='$ppswd1:'>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>PROPFIND of user on podB as user on podB</description>
			<request user='$puserid1:' pswd='$ppswd1:'>
				<method>PROPFIND</method>
				<ruri>$pcalendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='Access calendar homes via podB' only='yes'>
		<test name='1'>
			<description>PROPFIND of user on podA as user on podA</description>
			<request host2='yes'>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of user on podB as user on podA</description>
			<request host2='yes'>
				<method>PROPFIND</method>
				<ruri>$pcalendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of user on podA as user on podB</description>
			<request host2='yes' user='$puserid1:' pswd='$ppswd1:'>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>PROPFIND of user on podB as user on podB</description>
			<request host2='yes' user='$puserid1:' pswd='$ppswd1:'>
				<method>PROPFIND</method>
				<ruri>$pcalendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/count.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>
	
</caldavtest>
