=== apple/ccs-caldavtester/trunk/scripts/tests-pod/CalDAV/caldavtest.dtd
<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<!ELEMENT caldavtest (description?, require-feature?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT require-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>
	<!ELEMENT exclude-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT pause EMPTY>

	<!ELEMENT request (require-feature?, exclude-feature?, method, ruri*, header*, data?, verify*,
						graburi?, grabcount?, grabheader*, grabproperty*, grabelement*, grabcalproperty*, grabcalparameter*)>
		<!ATTLIST request host2 (yes|no) "no"
						 auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no"
						 iterate-data (yes|no) "no"
						 wait-for-success (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT data (content-type, filepath)>
			<!ATTLIST data substitutions (yes|no) "yes"
			               generate      (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>

		<!ELEMENT verify (require-feature?, exclude-feature?, callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value*)>
		
		<!ELEMENT graburi (#PCDATA)>

		<!ELEMENT grabcount (#PCDATA)>

		<!ELEMENT grabheader (name, variable)>
	
		<!ELEMENT grabproperty (property, variable)>
			<!ELEMENT property (#PCDATA)>
			<!ELEMENT variable (#PCDATA)>

		<!ELEMENT grabelement (name, parent*, variable+)>

		<!ELEMENT grabcalproperty (name, variable)>
		<!ELEMENT grabcalparameter (name, variable)>

	<!ELEMENT test-suite (require-feature?, exclude-feature?, test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no"
							only (yes|no) "no">
	
		<!ELEMENT test (require-feature?, exclude-feature?, description?, (request|pause)+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no"
						  only (yes|no) "no">

=== apple/ccs-caldavtester/trunk/scripts/tests/CalDAV/partitioning-scheduleimplicit.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Partitioning with auto-accept test</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>implicit-scheduling</feature>
		<feature>partitioning</feature>
	</require-feature>

	<start>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$inboxpath1:/</ruri>
			<ruri>$otherinboxpath1:/</ruri>
			<ruri>$otherinboxpath1:/</ruri>
		</request>
	</start>
	
	<test-suite name='#1 refresh across nodes' ignore='no'>
		<test name='1'>
			<description>Organizer invites Attendees</description>
			<request print-response='no'>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/partitioning/scheduleimplicit/suite1/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Organizer checks data</description>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/partitioning/scheduleimplicit/suite1/2.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Attendee Inbox Items</description>
			<request user="$otherid1:" pswd="$otherpswd1:" print-response='no'>
				<method>WAITDELETEALL 1</method>
				<ruri>$otherinboxpath1:/</ruri>
			</request>
			<request user="$otherid2:" pswd="$otherpswd2:" print-response='no'>
				<method>WAITDELETEALL 1</method>
				<ruri>$otherinboxpath2:/</ruri>
			</request>
		</test>
		<test name='4'>
			<description>Attendees have data</description>
			<request user="$otherid1:" pswd="$otherpswd1:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$othercalendarpath1:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/partitioning/scheduleimplicit/suite1/4.ics</value>
					</arg>
				</verify>
			</request>
			<request user="$otherid2:" pswd="$otherpswd2:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$othercalendarpath2:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/partitioning/scheduleimplicit/suite1/4.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='6'>
			<description>Attendee 1 -> Accepted</description>
			<request user="$otherid1:" pswd="$otherpswd1:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$othercalendarpath1:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request user="$otherid1:" pswd="$otherpswd1:" print-response='no'>
				<method>PUT</method>
				<ruri>$</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/partitioning/scheduleimplicit/suite1/5.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='7'>
			<description>Organizer Inbox Item</description>
			<request print-response='no'>
				<method>WAITDELETEALL 1</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
		</test>
		<test name='8'>
			<description>Organizer data changed</description>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/partitioning/scheduleimplicit/suite1/6.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='10'>
			<description>Attendee 2 no Inbox Item</description>
			<request user="$otherid2:" pswd="$otherpswd2:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$otherinboxpath2:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/partitioning/1.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='11'>
			<description>Attendee 2 data changed</description>
			<request user="$otherid2:" pswd="$otherpswd2:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$othercalendarpath2:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/partitioning/scheduleimplicit/suite1/7.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='12'>
			<description>Attendee 2 -> Decline</description>
			<request user="$otherid2:" pswd="$otherpswd2:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$othercalendarpath2:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request user="$otherid2:" pswd="$otherpswd2:" print-response='no'>
				<method>PUT</method>
				<ruri>$</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/partitioning/scheduleimplicit/suite1/8.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='13'>
			<description>Organizer Inbox Item</description>
			<request print-response='no'>
				<method>WAITDELETEALL 1</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
		</test>
		<test name='14'>
			<description>Organizer data changed</description>
			<request print-response='no'>
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/partitioning/scheduleimplicit/suite1/9.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='16'>
			<description>Attendee 1 no Inbox Item</description>
			<request user="$otherid1:" pswd="$otherpswd1:" print-response='no'>
				<method>PROPFIND</method>
				<ruri>$otherinboxpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/partitioning/1.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='17'>
			<description>Attendee 1 data changed</description>
			<request user="$otherid1:" pswd="$otherpswd1:" print-response='no'>
				<method>GETNEW</method>
				<ruri>$othercalendarpath1:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/partitioning/scheduleimplicit/suite1/10.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='18'>
			<description>Clean-up</description>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>DELETEALL</method>
				<ruri>$calendarpath1:/</ruri>
				<ruri>$inboxpath1:/</ruri>
				<ruri>$othercalendarpath1:/</ruri>
				<ruri>$otherinboxpath1:/</ruri>
				<ruri>$othercalendarpath2:/</ruri>
				<ruri>$otherinboxpath2:/</ruri>
			</request>
		</test>
	</test-suite>

	<end>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$otherinboxpath1:/</ruri>
			<ruri>$othercalendarpath1:/</ruri>
			<ruri>$inboxpath2:/</ruri>
			<ruri>$calendarpath2:/</ruri>
			<ruri>$rinboxpath1:/</ruri>
			<ruri>$rcalendarpath1:/</ruri>
		</request>
	</end>
	
</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CalDAV/implicitautomultiple.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test implicit scheduling for multiple auto-accept locations</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>auto-accept</feature>
		<feature>implicit-scheduling</feature>
	</require-feature>

	<start>
		<request user="$userid1:" pswd="$pswd1:">
			<method>GET</method>
			<ruri>$calendarpath1:/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>GET</method>
			<ruri>$calendarpath2:/</ruri>
		</request>
		<request>
			<method>DELETEALL</method>
			<ruri>$inboxpath1:/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>DELETEALL</method>
			<ruri>$inboxpath2:/</ruri>
		</request>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$rinboxpath1:/</ruri>
		</request>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$rcalendarpath1:/</ruri>
		</request>
	</start>
	
	<test-suite name='#1 Non-recurring without conflict' ignore='no'>
		<test name='1' ignore='no'>
			<description>Create new event</description>
			<request>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/automultiple/suite1/1.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>Two items in user01 Inbox</description>
			<request print-response="no">
				<method>WAITDELETEALL 2</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
		</test>
		<test name='3' ignore='no'>
			<description>One item in user01 Calendar</description>
			<request print-response="no">
				<method>GET</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/automultiple/suite1/2.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4' ignore='no'>
			<description>One item in user02 Inbox</description>
			<request user="$useradmin:" pswd="$pswdadmin:" print-response="no">
				<method>WAITDELETEALL 1</method>
				<ruri>$inboxpath2:/</ruri>
			</request>
		</test>
		<test name='5' ignore='no'>
			<description>One item in user02 calendar</description>
			<request user="$useradmin:" pswd="$pswdadmin:" wait-for-success="yes" print-response="no">
				<method>GETNEW</method>
				<ruri>$calendarpath2:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/automultiple/suite1/3.ics</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='6' ignore='no'>
			<description>No items in resource01 Inbox</description>
			<request user="$useradmin:" pswd="$pswdadmin:" print-response="no">
				<method>PROPFIND</method>
				<ruri>$rinboxpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/1.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='7' ignore='no'>
			<description>One item in resource01 Calendar</description>
			<request user="$useradmin:" pswd="$pswdadmin:" wait-for-success="yes" print-response="no">
				<method>GETNEW</method>
				<ruri>$rcalendarpath1:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/automultiple/suite1/4.ics</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>ORGANIZER:SCHEDULE-STATUS</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='8' ignore='no'>
			<description>No items in resource02 Inbox</description>
			<request user="$useradmin:" pswd="$pswdadmin:" print-response="no">
				<method>PROPFIND</method>
				<ruri>$rinboxpath2:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/implicit/1.xml</filepath>
				</data>
				<verify>
					<callback>multistatusItems</callback>
					<arg>
						<name>count</name>
						<value>0</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='9' ignore='no'>
			<description>One item in resource02 Calendar</description>
			<request user="$useradmin:" pswd="$pswdadmin:" wait-for-success="yes" print-response="no">
				<method>GETNEW</method>
				<ruri>$rcalendarpath2:/</ruri>
				<verify>
					<callback>calendarDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CalDAV/implicit/automultiple/suite1/4.ics</value>
					</arg>
					<arg>
						<name>filter</name>
						<value>ORGANIZER:SCHEDULE-STATUS</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='10' ignore='no'>
			<description>Clean-up inboxes</description>
			<request>
				<method>DELETEALL</method>
				<ruri>$inboxpath1:/</ruri>
			</request>
			<request user="$userid2:" pswd="$pswd2:">
				<method>DELETEALL</method>
				<ruri>$inboxpath2:/</ruri>
			</request>
			<request user="$useradmin:" pswd="$pswdadmin:">
				<method>DELETEALL</method>
				<ruri>$rinboxpath1:/</ruri>
			</request>
		</test>
	</test-suite>
	
	<end>
		<request>
			<method>DELETEALL</method>
			<ruri>$inboxpath1:/</ruri>
		</request>
		<request>
			<method>DELETEALL</method>
			<ruri>$calendarpath1:/</ruri>
		</request>
		<request user="$userid2:" pswd="$pswd2:">
			<method>DELETEALL</method>
			<ruri>$inboxpath2:/</ruri>
		</request>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$calendarpath2:/</ruri>
		</request>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$rinboxpath1:/</ruri>
		</request>
		<request user="$useradmin:" pswd="$pswdadmin:">
			<method>DELETEALL</method>
			<ruri>$rcalendarpath1:/</ruri>
		</request>
	</end>
	
</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CalDAV/managed-attachments-quota.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2012-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test managed attachments and quota</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>managed-attachments</feature>
		<feature>prefer-representation</feature>
		<feature>quota</feature>
	</require-feature>

	<start/>
	
	<test-suite name='Simple non-recurring, non-scheduled add attachment no prefer'>
		<test name='1' ignore='no'>
			<description>Quota check</description>
			<request print-response='no'>
				<exclude-feature>
					<feature>quota-on-resources</feature>
				</exclude-feature>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/managedattachments/quota/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}resourcetype</value>
						<value>{DAV:}quota-available-bytes</value>
						<value>{DAV:}quota-used-bytes$0</value>
					</arg>
				</verify>
				<grabelement>
					<name>$verify-property-prefix:/{DAV:}quota-used-bytes</name>
					<variable>$quota1:</variable>
				</grabelement>
			</request>
		</test>
		<test name='2' ignore='no'>
			<description>PUT event</description>
			<request end-delete='no'>
				<method>PUT</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<data>
					<content-type>text/calendar; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/managedattachments/quota/2.ics</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3' ignore='no'>
			<description>Quota check</description>
			<request print-response='no'>
				<exclude-feature>
					<feature>quota-on-resources</feature>
				</exclude-feature>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/managedattachments/quota/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}resourcetype</value>
						<value>{DAV:}quota-available-bytes</value>
						<value>{DAV:}quota-used-bytes$$quota1:</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4' ignore='no'>
			<description>Add attachment</description>
			<request>
				<method>POST</method>
				<ruri>$calendarpath1:/1.ics?action=attachment-add</ruri>
				<header>
					<name>Content-Disposition</name>
					<value>attachment;filename=test.txt</value>
				</header>
				<header>
					<name>Prefer</name>
					<value>return=representation</value>
				</header>
				<data>
					<content-type>text/plain</content-type>
					<filepath>Resource/CalDAV/managedattachments/quota/3.txt</filepath>
				</data>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>unwrap</name>
						<value/>
					</arg>
					<arg>
						<name>contains</name>
						<value>ATTACH</value>
					</arg>
				</verify>
				<grabheader>
					<name>Cal-Managed-ID</name>
					<variable>$managed-id:</variable>
				</grabheader>
			</request>
		</test>
		<test name='5' ignore='no'>
			<description>Quota check</description>
			<request print-response='no'>
				<exclude-feature>
					<feature>quota-on-resources</feature>
				</exclude-feature>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/managedattachments/quota/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}resourcetype</value>
						<value>{DAV:}quota-available-bytes</value>
						<value>{DAV:}quota-used-bytes!$quota1:</value>
					</arg>
				</verify>
				<grabelement>
					<name>$verify-property-prefix:/{DAV:}quota-used-bytes</name>
					<variable>$quota2:</variable>
				</grabelement>
			</request>
		</test>
		<test name='6' ignore='no'>
			<description>Update attachment</description>
			<request>
				<method>POST</method>
				<ruri>$calendarpath1:/1.ics?action=attachment-update&amp;managed-id=$managed-id:</ruri>
				<header>
					<name>Content-Disposition</name>
					<value>attachment;filename=test2.txt</value>
				</header>
				<header>
					<name>Prefer</name>
					<value>return=representation</value>
				</header>
				<data>
					<content-type>text/plain</content-type>
					<filepath>Resource/CalDAV/managedattachments/quota/4.txt</filepath>
				</data>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>unwrap</name>
						<value/>
					</arg>
					<arg>
						<name>contains</name>
						<value>ATTACH</value>
						<value>;FILENAME=test2.txt</value>
						<value>;FMTTYPE=text/plain</value>
						<value>;SIZE=</value>
						<value>;MANAGED-ID=</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='7' ignore='no'>
			<description>Quota check</description>
			<request print-response='no'>
				<exclude-feature>
					<feature>quota-on-resources</feature>
				</exclude-feature>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/managedattachments/quota/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}resourcetype</value>
						<value>{DAV:}quota-available-bytes</value>
						<value>{DAV:}quota-used-bytes!$quota2:</value>
					</arg>
				</verify>
				<grabelement>
					<name>$verify-property-prefix:/{DAV:}quota-used-bytes</name>
					<variable>$quota3:</variable>
				</grabelement>
			</request>
		</test>
		<test name='8' ignore='no'>
			<description>Delete calendar data</description>
			<request>
				<method>DELETE</method>
				<ruri>$calendarpath1:/1.ics</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='9' ignore='no'>
			<description>Quota check</description>
			<request print-response='no'>
				<exclude-feature>
					<feature>quota-on-resources</feature>
				</exclude-feature>
				<method>PROPFIND</method>
				<ruri>$calendarhome1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CalDAV/managedattachments/quota/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}resourcetype</value>
						<value>{DAV:}quota-available-bytes</value>
						<value>{DAV:}quota-used-bytes!$quota3:</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>

</caldavtest>

=== apple/ccs-caldavtester/trunk/scripts/tests/CardDAV/directory.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2013 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test GET on collections to ensure proper directory listing</description>
	
	<require-feature>
		<feature>carddav</feature>
	</require-feature>

	<start/>

	<test-suite name='GET on collections'>
		<test name='1'>
			<description>GET on root collection</description>
			<request>
				<method>GET</method>
				<ruri>$root:</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>GET on principals collection</description>
			<request>
				<method>GET</method>
				<ruri>$principalcollection:</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>GET on user principals collection</description>
			<request>
				<method>GET</method>
				<ruri>$principals_users:</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>GET on group principals collection</description>
			<request>
				<method>GET</method>
				<ruri>$principals_groups:</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>	
		<test name='5'>
			<description>GET on __uids__ principals collection</description>
			<request>
				<method>GET</method>
				<ruri>$principals_uids:</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='6'>
			<description>GET on addressbooks collection</description>
			<request>
				<method>GET</method>
				<ruri>$addressbooks:</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='7'>
			<description>GET on user addressbooks collection</description>
			<request>
				<method>GET</method>
				<ruri>$addressbooks_users:</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='8'>
			<description>GET on group addressbooks collection</description>
			<request>
				<method>GET</method>
				<ruri>$addressbooks_groups:</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='9'>
			<description>GET on __uids__ addressbooks collection</description>
			<request>
				<method>GET</method>
				<ruri>$addressbooks_uids:</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>
	
</caldavtest>
